### PR TITLE
Clean (no whitespace changes) of the Morse table changes.

### PR DESCRIPTION
**Pull request by slepp**
This is a clean branch of the Morse changes to reduce the table size/memory footprint. The other branch, morse, has a huge number of trailing whitespace removals. So, this is the easy one to read (and merge).

### CODE REVIEW

**Comment by nigelvh** [comment]
I've tested this locally, and it seems to cause some odd behaviors. I'm seeing that the tone frequency of the morse code has changed significantly, and it gets through a few "broken" tones (they have hiccups in the audio) before it goes silent and seems to never return from the morse call to end the transmission.

**Comment by slepp** [comment]
Can you try it by commenting out the MORSE_TABLE_PROGMEM define in the HamShield.cpp? I'll take a look at the rest of it as to why it wouldn't come out of there and was making hiccups. I'll get it compiled into an actual device here and see what it's up to. Also, the tone I set at 600, but I can bring that back up. Old habits of CW preferences there :)

**Comment by slepp** [comment]
Adjustments to how the loop is performed (use a for, instead of a while). The tone was brought back up to 1000. Just setting up a PWM filter here to test with. The non-return issue was the spaces weren't moving ahead in the buffer at all.

**Comment by nigelvh** [comment]
Ah, good to know on the 600. Some folks use 700. Perhaps we can set that as a preference in a future commit. I'll make that an issue/feature request. Meantime I will attempt after commenting out the MORSE_TABLE_PROGMEM as requested. And yes, D11 with a speaker attached should function similarly.

**Comment by slepp** [comment]
It was missing the delays for each async tone, which just made a mess of them. Those are back in now, and it sounds like it is working as expected.

**Comment by nigelvh** [comment]
Got around to testing this. Works as expected. Tones are good. Merging.

**Pull request merged**
